source "https://artifactory.globoi.com/artifactory/api/gems/gem-repos/"

ruby "2.6"

gem "awesome_print"

gem "rspec"
gem "rspec-collection_matchers"
gem "rspec-nc"
gem "timecop"

# guard
gem "guard"
gem "guard-rspec"
